// i18n translations
export const I18N = {
  uz: {
    appName: "Mylo",
    hello: "Salom",
    assistant: "Moliyaviy yordamchingiz",
    balance: "Joriy balans",
    todaySummary: "Bugungi xulosa",
    expenses: "Xarajatlar",
    income: "Daromad",
    home: "Bosh",
    stats: "Statistika",
    add: "Qo'shish",
    transactions: "Tranzaksiyalar",
    categories: "Kategoriyalar",
    limits: "Limitlar",
    goals: "Maqsadlar",
    debts: "Qarzlar",
    settings: "Sozlamalar",
    openBot: "Botni ochish",
    addTransaction: "Tranzaksiya qo'shish",
    editTransaction: "Tranzaksiyani tahrirlash",
    type: "Turi",
    expense: "Xarajat",
    incomeType: "Daromad",
    debtType: "Qarz",
    amount: "Summa",
    description: "Tavsif",
    category: "Kategoriya",
    date: "Sana",
    save: "Saqlash",
    cancel: "Bekor",
    delete: "O'chirish",
    edit: "Tahrirlash",
    empty: "Hozircha hech narsa yo'q",
    allTransactions: "Barcha tranzaksiyalar",
    filters: "Filtrlar",
    all: "Hammasi",
    today: "Bugun",
    week: "Bu hafta",
    month: "Bu oy",
    addCategory: "Kategoriya qo'shish",
    editCategory: "Kategoriyani tahrirlash",
    language: "Til",
    dataMode: "Ma'lumotlar rejimi",
    localMode: "Local (offline)",
    remoteMode: "Supabase (online)",
    sync: "Yangilash",
    syncOk: "Synclandi",
    syncFail: "Sync bo'lmadi",
    confirmDelete: "O'chirishni tasdiqlaysizmi?",
    quickAdd: "Tez qo'shish",
    addExpense: "Xarajat",
    addIncome: "Daromad",
    analytics: "Analitika",
    weekSpending: "Haftalik xarajat",
    monthSpending: "Oylik xarajat",
    topCategories: "Top kategoriyalar",
    noLimits: "Limitlar yo'q",
    noGoals: "Maqsadlar yo'q",
    noCategories: "Kategoriyalar yo'q",
    botHint: "Bot orqali ham qo'shishingiz mumkin",
    tgOpen: "Telegramda ochish",
    resetLocal: "Ma'lumotlarni tozalash",
    deposit: "Qo'shish",
    withdraw: "Olmoq",
    monthlyBudgets: "Oylik byudjetlar",
    spent: "Sarflangan",
    remaining: "Qolgan",
    viewAll: "Hammasini ko'rish",
    // Receipt scanner
    scan: "Skaner",
    scanReceipt: "Chekni skanerlash",
    receiptScanned: "Chek skanerlandi!",
    scanError: "Chekni o'qib bo'lmadi",
    aiPowered: "AI skanerlash",
    scanInfo: "Chekni suratga oling va AI avtomatik ravishda summa, sana va kategoriyani aniqlaydi.",
    takePhoto: "Suratga olish",
    chooseImage: "Rasm tanlash",
    scanTips: "Eng yaxshi natija uchun:",
    tipFlat: "Chekni tekis joyga qo'ying",
    tipLight: "Yaxshi yorug'lik, soya bo'lmasin",
    tipClear: "Butun chekni aniq oling",
    analyzing: "Chek tahlil qilinmoqda...",
    aiProcessing: "AI tranzaksiya ma'lumotlarini ajratmoqda",
    tryAgain: "Qayta urinish",
    enterManually: "Qo'lda kiritish",
    // Recurring & Goals
    recurring: "Takroriy",
    subscriptions: "Obunalar va to'lovlar",
    noRecurring: "Takroriy to'lovlar yo'q",
    addRecurring: "Takroriy qo'shish",
    frequency: "Chastota",
    next: "Keyingi",
    dueToday: "bugun to'lanishi kerak",
    execute: "Bajarish",
    pause: "To'xtatish",
    resume: "Davom ettirish",
    voice: "Ovoz",
    voiceHint: "Masalan: 'taksi 20000'",
    listening: "Eshitilmoqda...",
    processing: "Qayta ishlanmoqda...",
    accounts: "Hisoblar",
    reports: "Hisobotlar",
    more: "Ko'proq",
    tools: "Asboblar",
    frequentlyUsed: "Tez-tez ishlatiladi",
    allTools: "Barcha asboblar",
    search: "Qidirish",
    // Tool labels
    toolGoals: "Maqsadlar",
    toolGoalsDesc: "Moliyaviy maqsadlar",
    toolAnalytics: "Analitika",
    toolAnalyticsDesc: "Xarajatlar bo'yicha tahlil",
    toolLimits: "Xarajat limitlari",
    toolLimitsDesc: "Kategoriya byudjetlari",
    toolAccounts: "Hisoblar",
    toolAccountsDesc: "Hisoblaringizni boshqaring",
    toolReports: "Hisobotlar",
    toolReportsDesc: "Moliyaviy hisobotlar",
    toolSubscriptions: "Obunalar",
    toolSubscriptionsDesc: "Takroriy to'lovlarni kuzatish",
    toolRecurring: "Takroriy",
    toolRecurringDesc: "Takroriy tranzaksiyalar",
    toolBillSplit: "Xarajat bo'lish",
    toolBillSplitDesc: "Do'stlar bilan bo'lish",
    toolNetWorth: "Sof boylik",
    toolNetWorthDesc: "Jami boylikni kuzatish",
    toolInvestments: "Investitsiyalar",
    toolInvestmentsDesc: "Portfel kuzatuvi",
    toolCashFlow: "Pul oqimi",
    toolCashFlowDesc: "Balans prognozi",
    toolEnvelopes: "Konvertlar",
    toolEnvelopesDesc: "Konvert byudjetlash",
    toolDebtAssessment: "Qarz baholash",
    toolDebtAssessmentDesc: "Bunga qurbing yetadimi?",
    toolDebtPayoff: "Qarz to'lash",
    toolDebtPayoffDesc: "To'lash strategiyalari",
    toolSettings: "Sozlamalar",
    toolSettingsDesc: "Ilova sozlamalari",
    // Settings screen
    theme: "Mavzu",
    currency: "Valyuta",
    telegramBot: "Telegram bot",
    linked: "Ulangan",
    accountLinked: "Hisob ulangan",
    unlink: "Uzish",
    linkTelegram: "Telegramni ulash",
    syncData: "Sinxronlash",
    exportCSV: "CSV eksport",
    quickSetup: "Tez sozlamalar",
    help: "Yordam",
    learn: "O'rganish",
    resetData: "Ma'lumotlarni tozalash",
    resetConfirm: "Barcha ma'lumotlarni o'chirish?",
    resetWarning: "Barcha tranzaksiyalar, byudjetlar va maqsadlar o'chiriladi.",
    restartSetup: "Qayta sozlashni boshlash?",
    restartSetupDesc: "Tez qo'shish va afzalliklarni qayta sozlashingiz mumkin.",
    start: "Boshlash",
    guest: "Mehmon",
    yourPlan: "Sizning rejangiz",
    dataInCloud: "Ma'lumotlar bulutda",
    synced: "Sinxron",
    // Link Account modal
    linkTelegramTitle: "Telegramni ulash",
    linkTelegramDesc: "Telegram bot orqali tranzaksiyalarni sinxronlang",
    getLinkingCode: "Kodni olish",
    yourLinkingCode: "Sizning ulash kodingiz:",
    expiresIn: "10 daqiqada tugaydi",
    steps: "Qadamlar:",
    step1: "Oching",
    step2: "Yuboring",
    step3: "Tayyor!",
    orOpenBot: "Yoki botni to'g'ridan-to'g'ri oching:",
    // AI Copilot
    aiCopilot: "AI Kopilot",
    aiCopilotSubtitle: "Mylo moliyaviy yordamchi",
    analyzingFinances: "Moliyangizni tahlil qilmoqdaman...",
    refreshAnalysis: "Tahlilni yangilash",
    noWarnings: "Hammasi yaxshi! Ogohlantirishlar yo'q.",
    updated: "Yangilangan",
    analysisError: "Tahlil xatosi",
    // Buttons
    signIn: "Kirish / Ro'yxat",
    signOut: "Chiqish",
  },
  ru: {
    appName: "Mylo",
    hello: "Привет",
    assistant: "Ваш финансовый помощник",
    balance: "Баланс",
    todaySummary: "Сегодня",
    expenses: "Расходы",
    income: "Доходы",
    home: "Главная",
    stats: "Статистика",
    add: "Добавить",
    transactions: "Транзакции",
    categories: "Категории",
    limits: "Лимиты",
    goals: "Цели",
    debts: "Долги",
    settings: "Настройки",
    openBot: "Открыть бота",
    addTransaction: "Добавить транзакцию",
    editTransaction: "Редактировать транзакцию",
    type: "Тип",
    expense: "Расход",
    incomeType: "Доход",
    debtType: "Долг",
    amount: "Сумма",
    description: "Описание",
    category: "Категория",
    date: "Дата",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    empty: "Пока пусто",
    allTransactions: "Все транзакции",
    filters: "Фильтры",
    all: "Все",
    today: "Сегодня",
    week: "Неделя",
    month: "Месяц",
    addCategory: "Добавить категорию",
    editCategory: "Редактировать категорию",
    language: "Язык",
    dataMode: "Режим данных",
    localMode: "Local (offline)",
    remoteMode: "Supabase (online)",
    sync: "Обновить",
    syncOk: "Синхронизировано",
    syncFail: "Ошибка синхронизации",
    confirmDelete: "Удалить?",
    quickAdd: "Быстро добавить",
    addExpense: "Расход",
    addIncome: "Доход",
    analytics: "Аналитика",
    weekSpending: "За неделю",
    monthSpending: "За месяц",
    topCategories: "Топ категории",
    noLimits: "Нет лимитов",
    noGoals: "Нет целей",
    noCategories: "Нет категорий",
    botHint: "Можно добавлять через бота",
    tgOpen: "Открыть в Telegram",
    resetLocal: "Сбросить данные",
    deposit: "Пополнить",
    withdraw: "Снять",
    monthlyBudgets: "Месячные бюджеты",
    spent: "Потрачено",
    remaining: "Осталось",
    viewAll: "Смотреть все",
    // Receipt scanner
    scan: "Скан",
    scanReceipt: "Сканировать чек",
    receiptScanned: "Чек отсканирован!",
    scanError: "Не удалось прочитать чек",
    aiPowered: "AI-сканирование",
    scanInfo: "Сфотографируйте чек, и AI автоматически определит сумму, дату и категорию.",
    takePhoto: "Сделать фото",
    chooseImage: "Выбрать фото",
    scanTips: "Для лучших результатов:",
    tipFlat: "Положите чек на ровную поверхность",
    tipLight: "Хорошее освещение, без теней",
    tipClear: "Снимите весь чек целиком",
    analyzing: "Анализ чека...",
    aiProcessing: "AI извлекает данные транзакции",
    tryAgain: "Попробовать снова",
    enterManually: "Ввести вручную",
    // Recurring & Goals
    recurring: "Регулярные",
    subscriptions: "Подписки и счета",
    noRecurring: "Нет регулярных платежей",
    addRecurring: "Добавить регулярный",
    frequency: "Частота",
    next: "Следующий",
    dueToday: "к оплате сегодня",
    execute: "Выполнить",
    pause: "Пауза",
    resume: "Возобновить",
    voice: "Голос",
    voiceHint: "Например: 'такси 20000'",
    listening: "Слушаю...",
    processing: "Обработка...",
    accounts: "Счета",
    reports: "Отчёты",
    more: "Ещё",
    tools: "Инструменты",
    frequentlyUsed: "Часто используемые",
    allTools: "Все инструменты",
    search: "Поиск",
    // Tool labels
    toolGoals: "Цели",
    toolGoalsDesc: "Финансовые цели",
    toolAnalytics: "Аналитика",
    toolAnalyticsDesc: "Анализ расходов",
    toolLimits: "Лимиты расходов",
    toolLimitsDesc: "Бюджеты категорий",
    toolAccounts: "Счета",
    toolAccountsDesc: "Управление счетами",
    toolReports: "Отчёты",
    toolReportsDesc: "Финансовые отчёты",
    toolSubscriptions: "Подписки",
    toolSubscriptionsDesc: "Отслеживать регулярные платежи",
    toolRecurring: "Регулярные",
    toolRecurringDesc: "Регулярные транзакции",
    toolBillSplit: "Разделить счёт",
    toolBillSplitDesc: "Разделить с друзьями",
    toolNetWorth: "Чистый капитал",
    toolNetWorthDesc: "Отслеживать общее состояние",
    toolInvestments: "Инвестиции",
    toolInvestmentsDesc: "Отслеживание портфеля",
    toolCashFlow: "Денежный поток",
    toolCashFlowDesc: "Прогноз баланса",
    toolEnvelopes: "Конверты",
    toolEnvelopesDesc: "Бюджетирование конвертами",
    toolDebtAssessment: "Оценка долга",
    toolDebtAssessmentDesc: "Можете ли вы это позволить?",
    toolDebtPayoff: "Погашение долга",
    toolDebtPayoffDesc: "Стратегии погашения",
    toolSettings: "Настройки",
    toolSettingsDesc: "Настройки приложения",
    // Settings screen
    theme: "Тема",
    currency: "Валюта",
    telegramBot: "Telegram бот",
    linked: "Связан",
    accountLinked: "Аккаунт связан",
    unlink: "Отвязать",
    linkTelegram: "Связать Telegram",
    syncData: "Синхронизация",
    exportCSV: "Экспорт CSV",
    quickSetup: "Быстрые настройки",
    help: "Помощь",
    learn: "Обучение",
    resetData: "Сбросить все данные?",
    resetConfirm: "Сбросить все данные?",
    resetWarning: "Все транзакции, бюджеты и цели будут удалены.",
    restartSetup: "Перезапустить настройку?",
    restartSetupDesc: "Вы сможете заново настроить быстрые расходы и предпочтения.",
    start: "Начать",
    guest: "Гость",
    yourPlan: "Ваш план",
    dataInCloud: "Данные в облаке",
    synced: "Синхрон",
    // Link Account modal
    linkTelegramTitle: "Связать Telegram",
    linkTelegramDesc: "Синхронизируйте транзакции через Telegram бота",
    getLinkingCode: "Получить код",
    yourLinkingCode: "Ваш код связывания:",
    expiresIn: "Истекает через 10 минут",
    steps: "Шаги:",
    step1: "Откройте",
    step2: "Отправьте",
    step3: "Готово!",
    orOpenBot: "Или откройте бота напрямую:",
    // AI Copilot
    aiCopilot: "AI Копилот",
    aiCopilotSubtitle: "Финансовый помощник Mylo",
    analyzingFinances: "Анализирую ваши финансы...",
    refreshAnalysis: "Обновить анализ",
    noWarnings: "Всё отлично! Нет предупреждений.",
    updated: "Обновлено",
    analysisError: "Ошибка анализа",
    // Buttons
    signIn: "Войти / Регистрация",
    signOut: "Выйти",
  },
  en: {
    appName: "Mylo",
    hello: "Hello",
    assistant: "Your financial assistant",
    balance: "Balance",
    todaySummary: "Today",
    expenses: "Expenses",
    income: "Income",
    home: "Home",
    stats: "Stats",
    add: "Add",
    transactions: "Transactions",
    categories: "Categories",
    limits: "Budgets",
    goals: "Goals",
    debts: "Debts",
    settings: "Settings",
    openBot: "Open bot",
    addTransaction: "Add transaction",
    editTransaction: "Edit transaction",
    type: "Type",
    expense: "Expense",
    incomeType: "Income",
    debtType: "Debt",
    amount: "Amount",
    description: "Description",
    category: "Category",
    date: "Date",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    empty: "Nothing here yet",
    allTransactions: "All transactions",
    filters: "Filters",
    all: "All",
    today: "Today",
    week: "This week",
    month: "This month",
    addCategory: "Add category",
    editCategory: "Edit category",
    language: "Language",
    dataMode: "Data mode",
    localMode: "Local (offline)",
    remoteMode: "Supabase (online)",
    sync: "Sync",
    syncOk: "Synced",
    syncFail: "Sync failed",
    confirmDelete: "Delete?",
    quickAdd: "Quick add",
    addExpense: "Expense",
    addIncome: "Income",
    analytics: "Analytics",
    weekSpending: "Weekly",
    monthSpending: "Monthly",
    topCategories: "Top categories",
    noLimits: "No budgets",
    noGoals: "No goals",
    noCategories: "No categories",
    botHint: "You can add via bot too",
    tgOpen: "Open in Telegram",
    resetLocal: "Reset data",
    deposit: "Deposit",
    withdraw: "Withdraw",
    monthlyBudgets: "Monthly Budgets",
    spent: "Spent",
    remaining: "Remaining",
    viewAll: "View all",
    // Receipt scanner
    scan: "Scan",
    scanReceipt: "Scan Receipt",
    receiptScanned: "Receipt scanned!",
    scanError: "Could not read receipt",
    aiPowered: "AI-Powered Scanning",
    scanInfo: "Take a photo of your receipt and AI will automatically extract the amount, date, and category.",
    takePhoto: "Take Photo",
    chooseImage: "Choose Image",
    scanTips: "Tips for best results:",
    tipFlat: "Place receipt on flat surface",
    tipLight: "Good lighting, no shadows",
    tipClear: "Capture entire receipt clearly",
    analyzing: "Analyzing receipt...",
    aiProcessing: "AI is extracting transaction details",
    tryAgain: "Try Again",
    enterManually: "Enter Manually",
    // Recurring & Goals
    recurring: "Recurring",
    subscriptions: "Subscriptions & bills",
    noRecurring: "No recurring transactions",
    addRecurring: "Add Recurring",
    frequency: "Frequency",
    next: "Next",
    dueToday: "due today",
    execute: "Execute",
    pause: "Pause",
    resume: "Resume",
    voice: "Voice",
    voiceHint: "e.g. 'taxi 20000'",
    listening: "Listening...",
    processing: "Processing...",
    accounts: "Accounts",
    reports: "Reports",
    more: "More",
    tools: "Tools",
    frequentlyUsed: "Frequently Used",
    allTools: "All Tools",
    search: "Search",
    // Tool labels
    toolGoals: "Goals",
    toolGoalsDesc: "Financial goals",
    toolAnalytics: "Analytics",
    toolAnalyticsDesc: "Spending insights",
    toolLimits: "Spending Limits",
    toolLimitsDesc: "Set category budgets",
    toolAccounts: "Accounts",
    toolAccountsDesc: "Manage your accounts",
    toolReports: "Reports",
    toolReportsDesc: "Financial reports",
    toolSubscriptions: "Subscriptions",
    toolSubscriptionsDesc: "Track recurring payments",
    toolRecurring: "Recurring",
    toolRecurringDesc: "Recurring transactions",
    toolBillSplit: "Bill Split",
    toolBillSplitDesc: "Split expenses with friends",
    toolNetWorth: "Net Worth",
    toolNetWorthDesc: "Track total wealth",
    toolInvestments: "Investments",
    toolInvestmentsDesc: "Portfolio tracking",
    toolCashFlow: "Cash Flow",
    toolCashFlowDesc: "Forecast your balance",
    toolEnvelopes: "Envelopes",
    toolEnvelopesDesc: "Envelope budgeting",
    toolDebtAssessment: "Debt Assessment",
    toolDebtAssessmentDesc: "Can you afford it?",
    toolDebtPayoff: "Debt Payoff",
    toolDebtPayoffDesc: "Payoff strategies",
    toolSettings: "Settings",
    toolSettingsDesc: "App preferences",
    // Settings screen
    theme: "Theme",
    currency: "Currency",
    telegramBot: "Telegram Bot",
    linked: "Linked",
    accountLinked: "Account linked",
    unlink: "Unlink",
    linkTelegram: "Link Telegram",
    syncData: "Sync Data",
    exportCSV: "Export CSV",
    quickSetup: "Quick Setup",
    help: "Help",
    learn: "Learn",
    resetData: "Reset all data?",
    resetConfirm: "Reset all data?",
    resetWarning: "This will delete all your transactions, budgets, and goals.",
    restartSetup: "Restart setup wizard?",
    restartSetupDesc: "You'll be able to reconfigure quick adds and preferences.",
    start: "Start",
    guest: "Guest",
    yourPlan: "Your plan",
    dataInCloud: "Data in cloud",
    synced: "Synced",
    // Link Account modal
    linkTelegramTitle: "Link Telegram",
    linkTelegramDesc: "Sync transactions via Telegram bot",
    getLinkingCode: "Get Linking Code",
    yourLinkingCode: "Your linking code:",
    expiresIn: "Expires in 10 minutes",
    steps: "Steps:",
    step1: "Open",
    step2: "Send",
    step3: "Done!",
    orOpenBot: "Or open the bot directly:",
    // AI Copilot
    aiCopilot: "AI Copilot",
    aiCopilotSubtitle: "Mylo Financial Assistant",
    analyzingFinances: "Analyzing your finances...",
    refreshAnalysis: "Refresh Analysis",
    noWarnings: "All good! No warnings.",
    updated: "Updated",
    analysisError: "Analysis error",
    // Buttons
    signIn: "Sign In / Sign Up",
    signOut: "Sign Out",
  },
};

export const LANGS = [
  { key: "uz", label: "O'zbek", flag: "🇺🇿" },
  { key: "ru", label: "Русский", flag: "🇷🇺" },
  { key: "en", label: "English", flag: "🇬🇧" },
];

export type LangKey = "uz" | "ru" | "en";

// Add new translation keys for receipt scanner
export type Translation = typeof I18N.en;

// Default categories with colors matching Revolut's clean style
export const DEFAULT_CATEGORIES = {
  expense: [
    { id: "food", uz: "Oziq-ovqat", ru: "Продукты", en: "Food", emoji: "🍔", color: "#FF6B6B" },
    { id: "restaurants", uz: "Restoranlar", ru: "Рестораны", en: "Restaurants", emoji: "🍽️", color: "#FF8787" },
    { id: "coffee", uz: "Kofe", ru: "Кофе", en: "Coffee", emoji: "☕", color: "#D4A574" },
    { id: "transport", uz: "Transport", ru: "Транспорт", en: "Transport", emoji: "🚗", color: "#4DABF7" },
    { id: "taxi", uz: "Taksi", ru: "Такси", en: "Taxi", emoji: "🚕", color: "#FFD43B" },
    { id: "fuel", uz: "Benzin", ru: "Бензин", en: "Fuel", emoji: "⛽", color: "#FAB005" },
    { id: "bills", uz: "Kommunal", ru: "Коммунальные", en: "Bills", emoji: "💡", color: "#12B886" },
    { id: "shopping", uz: "Xaridlar", ru: "Покупки", en: "Shopping", emoji: "🛍️", color: "#BE4BDB" },
    { id: "health", uz: "Salomatlik", ru: "Здоровье", en: "Health", emoji: "💊", color: "#F06595" },
    { id: "education", uz: "Ta'lim", ru: "Образование", en: "Education", emoji: "📚", color: "#4DABF7" },
    { id: "entertainment", uz: "Ko'ngilochar", ru: "Развлечения", en: "Fun", emoji: "🎬", color: "#9775FA" },
    { id: "other", uz: "Boshqa", ru: "Другое", en: "Other", emoji: "📦", color: "#868E96" },
  ],
  income: [
    { id: "salary", uz: "Oylik", ru: "Зарплата", en: "Salary", emoji: "💰", color: "#51CF66" },
    { id: "freelance", uz: "Frilanser", ru: "Фриланс", en: "Freelance", emoji: "💻", color: "#40C057" },
    { id: "bonus", uz: "Bonus", ru: "Бонус", en: "Bonus", emoji: "🎉", color: "#F59F00" },
    { id: "other_income", uz: "Boshqa", ru: "Другое", en: "Other", emoji: "💵", color: "#82C91E" },
  ],
  debt: [
    { id: "borrowed", uz: "Qarz oldim", ru: "Взял в долг", en: "Borrowed", emoji: "🤝", color: "#FF6B6B" },
    { id: "lent", uz: "Qarz berdim", ru: "Дал в долг", en: "Lent", emoji: "💸", color: "#51CF66" },
    { id: "loan_payment", uz: "Qarz to'lovi", ru: "Платёж по долгу", en: "Debt payment", emoji: "🏦", color: "#339AF0" },
    { id: "credit", uz: "Kredit karta", ru: "Кредитка", en: "Credit card", emoji: "💳", color: "#845EF7" },
  ],
};

export type CategoryType = "expense" | "income" | "debt";
export type Category = typeof DEFAULT_CATEGORIES.expense[0];
